### PR TITLE
Github Pages

### PR DESCRIPTION
**Pull request by Emadgnia**
If you run the following command, you'll get the DocC compiled and you can put the output in the docs folder and enable the github pages for free, I'v already pushed it my branch.
https://emadgnia.github.io/BuildABuddyKit/tutorials/table-of-contents/
```
$(xcrun --find docc) process-archive \
transform-for-static-hosting DOCCARCHIVEPATH \            
--output-path OUTPUPATH  \
--hosting-base-path /BuildABuddyKit
```

### CODE REVIEW

**Comment by simonbs** [comment]
Hi @Emadgnia! Thanks for sharing this! This seems like the perfect way to host the documentation. I'll try to set it up.

I'm hesitant to merge your PR because of the way the branches in this repository is structured (step-1, step-2, ...). I'll have a closer look at the best way to integrate this into the repository and the branches later.

**Comment by Emadgnia** [comment]
> Hi @Emadgnia! Thanks for sharing this! This seems like the perfect way to host the documentation. I'll try to set it up.
> 
> 
> 
> I'm hesitant to merge your PR because of the way the branches in this repository is structured (step-1, step-2, ...). I'll have a closer look at the best way to integrate this into the repository and the branches later.

Sure @simonbs 
It was just a note that you can do it like this, didn't want to have it merged necessarily 🙌👍

**Comment by finestructure** [comment]
I've just added the package to the Package Index, so we could host the docs there if you like?

**Comment by simonbs** [comment]
> I've just added the package to the Package Index, so we could host the docs there if you like?

Thanks! This isn't a "real" package though. It's meant for learning purposes only 😊

**Comment by finestructure** [comment]
Yeah, but it looks like it'd be a nice resource for writing docs?

I can take it back out if you prefer, just let me know!

**Comment by simonbs** [comment]
> I can take it back out if you prefer, just let me know!

Totally fine to keep it there with me. I just wanted to ensure you know it's not a "real" package.

I'd be happy to have the documentation available on Swift Package Index.

**Pull request closed without merging**
